server:
    # \u7AEF\u53E3\u53F7
    port: 8981
spring:
    datasource:
        # \u9A71\u52A8
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/csjpa?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
        password: root
        username: root
    jpa:
        hibernate:
            #none：默认值，什么都不做，每次启动项目，不会对数据库进行任何验证和操作
            #create：每次运行项目，没有表会新建表，如果表内有数据会被清空
            #create-drop：每次程序结束的时候会清空表
            #update：每次运行程序，没有表会新建表，但是表内有数据不会被清空，只会更新表结构。
            #validate：运行程序会校验数据与数据库的字段类型是否相同，不同会报错
            ddl-auto: update

swagger:
    enable: true
