server:
    # \u7AEF\u53E3\u53F7
    port: 8981
spring:
    datasource:
        # \u9A71\u52A8
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://127.0.0.1:3306/csjpa?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
        password: root
        username: root
    jpa:
        hibernate:
            #none：默认值，什么都不做，每次启动项目，不会对数据库进行任何验证和操作
            #create：每次运行项目，没有表会新建表，如果表内有数据会被清空
            #create-drop：每次程序结束的时候会清空表
            #update：每次运行程序，没有表会新建表，但是表内有数据不会被清空，只会更新表结构。
            #validate：运行程序会校验数据与数据库的字段类型是否相同，不同会报错
            ddl-auto: update
    #  security的      配置用户的基本信息
    security:
        user:
            password: 111
            name: aaa
swagger:
    enable: true
jwt:
    header: Authorization
    # 令牌前缀
    token-start-with: Bearer
    # 使用Base64对该令牌进行编码
    base64-secret: MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEA0WaRbzhdnly+S5EqfuP7X3q1X3nsUuGdFgjd/nQdx7jYilNUmaKdoqxAXt7C76gR7ynL3Kuf7gMLPk+7Vj8P+wIDAQABAkAjd1fSmp1goRyp9+BWtY5x0Xq+vQvFzeipPr86xbf1h455w+wnDG0BmN5mdyDrCbh/JBApb/QqXvg4k5lSoVghAiEA/wAfYOVESFlBQv7xjIFIA1Z3k2QsDuYK/iaeeqb4Bx8CIQDSOLBbJKBK0M0Nz5vcQDAwV0bDRpZQ3Lj7qtbBattnpQIhAIv9+jwMwcbiUUTBh8R2OR2z+6OMK+/l9QUAGKMHRUVLAiBRziuanCsgUhapnDObxwK5nQz1ap+OAgaeMMH3bHzK3QIhAJab5MDInyX6E/yarqcPaWKHXzqiMTStPtUitVNWx7Ia
    # 令牌过期时间 此处单位/毫秒
    token-validity-in-seconds: 14400000